/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package jframe.Ekran;

import connmysqlhospital.connmysqlxestexana;
import entityhekim.Hekim;
import entitysobe.sobe;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Rafael
 */
public class Hekimdialog extends javax.swing.JDialog {

    private List<Hekim> listofhekim;
    private Hekim selectedhekim;
    private final connmysqlxestexana conn;
    private final List<sobe> listofsobe;

    /**
     * Creates new form Hekimdialog
     */
    public Hekimdialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
         setTitle("Hekimler");
        action("init");
       conn = new connmysqlxestexana();
        
        listofhekim = conn.ekranacixarmaemrihekim("");
       fillthetable(listofhekim);
       listofsobe = conn.ekranacixarmasobe("");
        for (sobe s : listofsobe) {
            jComboBoxsobe.addItem(s.getAd());
        }
       
    }
    
private void fillthetable(List<Hekim>list){
DefaultTableModel tmodel = new DefaultTableModel(){
    @Override
    public boolean isCellEditable(int i, int i1) {
        return false;}};
tmodel.addColumn("Ad");
tmodel.addColumn("Soyad");
tmodel.addColumn("Telefon");
tmodel.addColumn("Vezife");
tmodel.addColumn("Sobe");
jTable1.setModel(tmodel);
    for (Hekim hekim : list) {
       tmodel.insertRow(jTable1.getRowCount(), 
               new Object[] { hekim.getAd(),
                              hekim.getSoyad(),
                              hekim.getTelefon(),
                              hekim.getVezife(),
                              conn.idgoreekrancixarsobe(hekim.getIdsobe()).get(0).getAd()
       });
    }
}   
private void clear(){
jTextField1ad.setText(null);
jTextFieldaxtar.setText(null);

jTextFieldsoyad.setText(null);
jTextFieldtelefon.setText(null);
jTextFieldvezife.setText(null);}    


private void textfieldproperties(boolean done){
jTextField1ad.setEnabled(done);
jTextFieldsoyad.setEnabled(done);
jTextFieldtelefon.setEnabled(done);
jTextFieldvezife.setEnabled(done);
jComboBoxsobe.setEnabled(done);
}



private void buttonproperties(boolean New, boolean Edit, boolean SCC, boolean Del, boolean CAN){
jButtonnew.setEnabled(New);
jButtonedit.setEnabled(Edit);
jButtonsave.setEnabled(SCC);
jButtonclear.setEnabled(SCC);
jButtoncancel.setEnabled(CAN);
jButtondelete.setEnabled(Del);}



private void action(String actionname){
boolean New , Edit , SCC , CAN, done , del;
   switch(actionname){
       case "New": { New=false;
                     Edit=false;
                     SCC=true;
                     done=true;
                     del=false;
                     CAN=true;
                   break;}
      case "Edit":{  New=false;
                     Edit=false;
                     SCC=true;
                     done=true;
                     del=false;
                     CAN=true;
                   break;}
      case "Table":{ New=true;
                     Edit=true;
                     SCC=false;
                     done=false;
                     del=true;
                     CAN=true;
                     break;}
    
      default:       New=true;
                     Edit=false;
                     SCC=false;
                     done=false;
                     del=false;
                     CAN=true;
                     clear();
                    
    }
    buttonproperties(New, Edit, SCC, del, CAN);
    textfieldproperties(done);
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelad = new javax.swing.JLabel();
        jTextField1ad = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTextFieldsoyad = new javax.swing.JTextField();
        jTextFieldvezife = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTextFieldtelefon = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jButtonnew = new javax.swing.JButton();
        jButtonedit = new javax.swing.JButton();
        jButtonsave = new javax.swing.JButton();
        jButtonclear = new javax.swing.JButton();
        jButtoncancel = new javax.swing.JButton();
        jButtondelete = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jTextFieldaxtar = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jComboBoxaxtar = new javax.swing.JComboBox<>();
        jButtonaxtar = new javax.swing.JButton();
        jComboBoxsobe = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabelad.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabelad.setText("Ad:");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Soyad:");

        jTextFieldsoyad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldsoyadActionPerformed(evt);
            }
        });

        jTextFieldvezife.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldvezifeActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("Telefon:");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("Vezife:");

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setText("Söbə:");

        jButtonnew.setText("New");
        jButtonnew.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonnewActionPerformed(evt);
            }
        });

        jButtonedit.setText("Edit");
        jButtonedit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtoneditActionPerformed(evt);
            }
        });

        jButtonsave.setText("Save");
        jButtonsave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonsaveActionPerformed(evt);
            }
        });

        jButtonclear.setText("Clear");
        jButtonclear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonclearActionPerformed(evt);
            }
        });

        jButtoncancel.setText("Cancel");
        jButtoncancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtoncancelActionPerformed(evt);
            }
        });

        jButtondelete.setText("Delete");
        jButtondelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtondeleteActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jTextFieldaxtar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldaxtarActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setText("Axtar:");

        jComboBoxaxtar.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Ad", "Soyad", "PinKod", "Telefon" }));
        jComboBoxaxtar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxaxtarActionPerformed(evt);
            }
        });

        jButtonaxtar.setText("Axtar");
        jButtonaxtar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonaxtarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabelad)
                                .addGap(46, 46, 46)
                                .addComponent(jTextField1ad, javax.swing.GroupLayout.PREFERRED_SIZE, 327, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(23, 23, 23)
                                .addComponent(jTextFieldsoyad, javax.swing.GroupLayout.PREFERRED_SIZE, 327, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel6)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButtonnew)
                                .addGap(18, 18, 18)
                                .addComponent(jButtonedit)
                                .addGap(18, 18, 18)
                                .addComponent(jButtonsave)
                                .addGap(18, 18, 18)
                                .addComponent(jButtonclear)
                                .addGap(18, 18, 18)
                                .addComponent(jButtoncancel)
                                .addGap(18, 18, 18)
                                .addComponent(jButtondelete))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(66, 66, 66)
                                    .addComponent(jComboBoxsobe, 0, 328, Short.MAX_VALUE))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel4)
                                        .addComponent(jLabel5))
                                    .addGap(18, 18, 18)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jTextFieldtelefon, javax.swing.GroupLayout.DEFAULT_SIZE, 327, Short.MAX_VALUE)
                                        .addComponent(jTextFieldvezife)))))
                        .addGap(0, 278, Short.MAX_VALUE))
                    .addComponent(jScrollPane1))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jComboBoxaxtar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextFieldaxtar, javax.swing.GroupLayout.PREFERRED_SIZE, 293, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButtonaxtar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelad)
                    .addComponent(jTextField1ad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jTextFieldsoyad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jTextFieldtelefon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jTextFieldvezife, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jComboBoxsobe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonsave, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButtonnew)
                        .addComponent(jButtonedit)
                        .addComponent(jButtonclear)
                        .addComponent(jButtoncancel)
                        .addComponent(jButtondelete)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jComboBoxaxtar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldaxtar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonaxtar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 376, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldaxtarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldaxtarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldaxtarActionPerformed

    private void jComboBoxaxtarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxaxtarActionPerformed
    int index = jComboBoxaxtar.getSelectedIndex();
   
    
    if(index==0){List<Hekim>list = conn.adagoreekranacixhek(jTextFieldaxtar.getText());
        fillthetable(list);}else{
    if(index==1){List<Hekim>list = conn.soyadgoreekrancixarhek(jTextFieldaxtar.getText());
        fillthetable(list);}else{
    if(index==2){
    List<Hekim>list =conn.telefgorecixarhek(jTextFieldaxtar.getText());
        fillthetable(list);}else{
    if(index==3){
    List<Hekim>list = conn.vezifegorecixarhek(jTextFieldaxtar.getText());
        fillthetable(list);}}}}
   
    
            
    }//GEN-LAST:event_jComboBoxaxtarActionPerformed

    private void jButtonaxtarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonaxtarActionPerformed
       if(!jTextFieldaxtar.getText().equals("")){  jComboBoxaxtarActionPerformed(evt);}else{
       JOptionPane.showMessageDialog(this, "Birsey daxil edin");}    }//GEN-LAST:event_jButtonaxtarActionPerformed

    private void jTextFieldsoyadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldsoyadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldsoyadActionPerformed

    private void jTextFieldvezifeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldvezifeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldvezifeActionPerformed

    private void jButtonnewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonnewActionPerformed
        action("New");    }//GEN-LAST:event_jButtonnewActionPerformed

    private void jButtoneditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtoneditActionPerformed
          int index = jTable1.getSelectedRow();
          selectedhekim = listofhekim.get(index);
          jTextField1ad.setText(selectedhekim.getAd());
          jTextFieldsoyad.setText(selectedhekim.getSoyad());
          jTextFieldtelefon.setText(selectedhekim.getTelefon());
          jTextFieldvezife.setText(selectedhekim.getVezife());
         

        action("Edit");    }//GEN-LAST:event_jButtoneditActionPerformed

    private void jButtoncancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtoncancelActionPerformed
       
        action("Cancel");    }//GEN-LAST:event_jButtoncancelActionPerformed

    private void jButtondeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtondeleteActionPerformed
           int index = jTable1.getSelectedRow();
           int id = listofhekim.get(index).getIdhekim();
           connmysqlxestexana conn = new connmysqlxestexana();
          int n = JOptionPane.showConfirmDialog(this,  "Silmeye Eminsiniz?!","Xeberdarliq!",JOptionPane.OK_CANCEL_OPTION);
          if(n==0){
          conn.deletehekim(id);
          listofhekim.remove(index);
              fillthetable(listofhekim);}
          
        action("del");    }//GEN-LAST:event_jButtondeleteActionPerformed

    private void jButtonclearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonclearActionPerformed
clear();    }//GEN-LAST:event_jButtonclearActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
       if(evt.getClickCount()==2){
           action("Table");
       }
    }//GEN-LAST:event_jTable1MouseClicked

    private void jButtonsaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonsaveActionPerformed
      if(!jTextField1ad.getText().equals("")&&!jTextFieldsoyad.getText().equals("")&&!jTextFieldtelefon.getText().equals("")&&!jTextFieldvezife.getText().equals("")){
       int id=0;
          if(selectedhekim!=null){
          id=selectedhekim.getIdhekim();}
          
          
          
       connmysqlxestexana conn = new connmysqlxestexana();
      Hekim h = new Hekim();
      h.setAd(jTextField1ad.getText());
      h.setSoyad(jTextFieldsoyad.getText());
      h.setTelefon(jTextFieldtelefon.getText());
      h.setVezife(jTextFieldvezife.getText());
      h.setIdhekim(id);
      sobe selectedsobe = listofsobe.get(jComboBoxsobe.getSelectedIndex());
      h.setIdsobe(selectedsobe.getIdsobe());
      conn.insertupdatehekim(h);
      listofhekim=conn.ekranacixarmaemrihekim("");
          fillthetable(listofhekim);
          
          action("");
          selectedhekim=null;
      clear();
      }else{JOptionPane.showMessageDialog(null, "Bu xanalar bos qala bilmez!!!");}
    }//GEN-LAST:event_jButtonsaveActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Hekimdialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Hekimdialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Hekimdialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Hekimdialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Hekimdialog dialog = new Hekimdialog(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonaxtar;
    private javax.swing.JButton jButtoncancel;
    private javax.swing.JButton jButtonclear;
    private javax.swing.JButton jButtondelete;
    private javax.swing.JButton jButtonedit;
    private javax.swing.JButton jButtonnew;
    private javax.swing.JButton jButtonsave;
    private javax.swing.JComboBox<String> jComboBoxaxtar;
    private javax.swing.JComboBox<String> jComboBoxsobe;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabelad;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1ad;
    private javax.swing.JTextField jTextFieldaxtar;
    private javax.swing.JTextField jTextFieldsoyad;
    private javax.swing.JTextField jTextFieldtelefon;
    private javax.swing.JTextField jTextFieldvezife;
    // End of variables declaration//GEN-END:variables
}
