/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package jframe.Ekran;

/**
 *
 * @author Rafael
 */
public class Hospital extends javax.swing.JFrame {

    /**
     * Creates new form Hospital
     */
    public Hospital() {
        initComponents();
        setTitle("Hospital");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jButtonhekimler = new javax.swing.JButton();
        jButtonsobe = new javax.swing.JButton();
        jButtonpasientler = new javax.swing.JButton();
        jButtonqeydiyyat = new javax.swing.JButton();

        jLabel2.setText("jLabel2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("XOS GELMISIZ!!");

        jButtonhekimler.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButtonhekimler.setText("Hekimler");
        jButtonhekimler.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonhekimlerActionPerformed(evt);
            }
        });

        jButtonsobe.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButtonsobe.setText("Sobe");
        jButtonsobe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonsobeActionPerformed(evt);
            }
        });

        jButtonpasientler.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButtonpasientler.setText("Pasient");
        jButtonpasientler.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonpasientlerActionPerformed(evt);
            }
        });

        jButtonqeydiyyat.setText("Qeydiyyat");
        jButtonqeydiyyat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonqeydiyyatActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(52, 52, 52)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButtonpasientler, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonhekimler)
                            .addComponent(jButtonqeydiyyat)
                            .addComponent(jButtonsobe, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButtonhekimler)
                .addGap(35, 35, 35)
                .addComponent(jButtonpasientler)
                .addGap(35, 35, 35)
                .addComponent(jButtonqeydiyyat)
                .addGap(35, 35, 35)
                .addComponent(jButtonsobe)
                .addContainerGap(42, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonhekimlerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonhekimlerActionPerformed
       Hekimdialog h = new Hekimdialog(this, rootPaneCheckingEnabled);
      h.setVisible(rootPaneCheckingEnabled);
    }//GEN-LAST:event_jButtonhekimlerActionPerformed

    private void jButtonpasientlerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonpasientlerActionPerformed
       Pasiyentekrani p = new Pasiyentekrani(this, rootPaneCheckingEnabled);
       p.setVisible(rootPaneCheckingEnabled);
    }//GEN-LAST:event_jButtonpasientlerActionPerformed

    private void jButtonqeydiyyatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonqeydiyyatActionPerformed
      Qeydiyyatdialog qeyd = new Qeydiyyatdialog(this, true);
       qeyd.setVisible(true);
    }//GEN-LAST:event_jButtonqeydiyyatActionPerformed

    private void jButtonsobeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonsobeActionPerformed
       Sobedialog s = new Sobedialog(this, rootPaneCheckingEnabled);
       s.setVisible(rootPaneCheckingEnabled);
    }//GEN-LAST:event_jButtonsobeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Hospital.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Hospital.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Hospital.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Hospital.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Hospital().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonhekimler;
    private javax.swing.JButton jButtonpasientler;
    private javax.swing.JButton jButtonqeydiyyat;
    private javax.swing.JButton jButtonsobe;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
