/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package jframe.Ekran;

import connmysqlhospital.connmysqlxestexana;
import entityPasiyent.Pasiyent;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Rafael
 */
public class Pasiyentekrani extends javax.swing.JDialog {

    private final connmysqlxestexana conn;
    private List<Pasiyent> listofpasiyents;
    private Pasiyent selectedpasiyent;

    /**
     * Creates new form Pasiyent
     */
    public Pasiyentekrani(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
         setTitle("Pasiyent");
        action("init");
       conn = new connmysqlxestexana();
       listofpasiyents = conn.ekranacixarmaemripasiyent("");
       
        fillthetable(listofpasiyents);
    }
    
private void fillthetable(List<Pasiyent>list){
    DefaultTableModel tmodel = new DefaultTableModel(){
        @Override
        public boolean isCellEditable(int i, int i1) {
            return false;}};
    tmodel.addColumn("Ad");
    tmodel.addColumn("Soyad");
    tmodel.addColumn("Pinkod");
    tmodel.addColumn("Telefon");
    tmodel.addColumn("Adress");
    jTable1.setModel(tmodel);
    for (Pasiyent pas : list){ 
     tmodel.insertRow(jTable1.getRowCount(), new Object[]{pas.getAd(),pas.getSoyad(),pas.getPinkod(),pas.getTelefon(),pas.getAdres()});
    }
   }    
  
private void clear(){
jTextFieldname.setText(null);
jTextFieldsurname.setText(null);
jTextFieldpinkod.setText(null);
jTextFieldphone.setText(null);
jTextFieldadress.setText(null);
jTextFieldaxtar.setText(null);

}    
private void textfealdproperties(boolean done){
jTextFieldname.setEnabled(done);
jTextFieldsurname.setEnabled(done);
jTextFieldpinkod.setEnabled(done);
jTextFieldphone.setEnabled(done);
jTextFieldadress.setEnabled(done);

}
private void buttonproperties(boolean New, boolean Edit, boolean SCC, boolean Del, boolean CAN){
jButtonnew.setEnabled(New);
jButtonedit.setEnabled(Edit);
jButtonsave.setEnabled(SCC);
jButtonclear.setEnabled(SCC);
jButtoncancel.setEnabled(CAN);
jButtondelete.setEnabled(Del);

}
private void action(String actionname){
    boolean New , done , SCC , Del, CAN , Edit ; 
    switch (actionname){
        case "New":{
            New = false;
            Edit=false;
            done= true; 
            SCC=true;
            Del=false;
            CAN=true;
           
               break;     
        }
        case "Table" :{
            New = true;
            Edit=true;
            done= false; 
            SCC=false;
            Del=true;
            CAN=true;
               break;    
        }
        case "Edit" :{
            New = false;
            Edit=false;
            done= true; 
            SCC=true;
            Del=false;
            CAN=true;
               break;    
        }
        default:
            New = true;
            Edit=false;
            done= false; 
            SCC=false;
            Del=false;
            CAN=true;
            
               break;  
    }
    textfealdproperties(done);
    buttonproperties(New, Edit, SCC,Del ,CAN );
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jTextFieldname = new javax.swing.JTextField();
        jTextFieldsurname = new javax.swing.JTextField();
        jTextFieldpinkod = new javax.swing.JTextField();
        jTextFieldphone = new javax.swing.JTextField();
        jTextFieldadress = new javax.swing.JTextField();
        jButtonnew = new javax.swing.JButton();
        jButtonedit = new javax.swing.JButton();
        jButtonsave = new javax.swing.JButton();
        jButtonclear = new javax.swing.JButton();
        jButtoncancel = new javax.swing.JButton();
        jButtondelete = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jTextFieldaxtar = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jButtaxtar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("Ad:");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Soyad:");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Pinkod");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("Telefon");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("Adress");

        jTextFieldadress.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldadressActionPerformed(evt);
            }
        });

        jButtonnew.setText("New");
        jButtonnew.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonnewActionPerformed(evt);
            }
        });

        jButtonedit.setText("Edit");
        jButtonedit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtoneditActionPerformed(evt);
            }
        });

        jButtonsave.setText("Save");
        jButtonsave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonsaveActionPerformed(evt);
            }
        });

        jButtonclear.setText("Clear");
        jButtonclear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonclearActionPerformed(evt);
            }
        });

        jButtoncancel.setText("Cancel");
        jButtoncancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtoncancelActionPerformed(evt);
            }
        });

        jButtondelete.setText("Delete");
        jButtondelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtondeleteActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jTable1MouseEntered(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jTextFieldaxtar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldaxtarActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setText("Axtar:");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Ad", "Soyad", "PinKod", "Telefon" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        jButtaxtar.setText("Axtar");
        jButtaxtar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtaxtarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel3))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jTextFieldpinkod)
                                    .addComponent(jTextFieldsurname, javax.swing.GroupLayout.DEFAULT_SIZE, 283, Short.MAX_VALUE)
                                    .addComponent(jTextFieldname)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextFieldadress, javax.swing.GroupLayout.PREFERRED_SIZE, 283, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextFieldphone, javax.swing.GroupLayout.PREFERRED_SIZE, 283, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButtonnew)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButtonedit)
                                .addGap(18, 18, 18)
                                .addComponent(jButtonsave))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jTextFieldaxtar, javax.swing.GroupLayout.PREFERRED_SIZE, 293, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jButtaxtar))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButtonclear)
                                .addGap(18, 18, 18)
                                .addComponent(jButtoncancel)
                                .addGap(18, 18, 18)
                                .addComponent(jButtondelete))))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 718, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(485, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextFieldname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextFieldsurname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jTextFieldpinkod, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jTextFieldphone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jTextFieldadress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonnew)
                    .addComponent(jButtonedit)
                    .addComponent(jButtonsave)
                    .addComponent(jButtonclear)
                    .addComponent(jButtoncancel)
                    .addComponent(jButtondelete))
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldaxtar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtaxtar))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 371, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(686, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldadressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldadressActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldadressActionPerformed

    private void jButtonnewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonnewActionPerformed
        action("New");    }//GEN-LAST:event_jButtonnewActionPerformed

    private void jButtoneditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtoneditActionPerformed
        action("Edit");
        int index = jTable1.getSelectedRow();
        selectedpasiyent = listofpasiyents.get(index);
        jTextFieldname.setText(selectedpasiyent.getAd());
        jTextFieldsurname.setText(selectedpasiyent.getSoyad());
        jTextFieldpinkod.setText(selectedpasiyent.getPinkod());
        jTextFieldphone.setText(selectedpasiyent.getTelefon());
        jTextFieldadress.setText(selectedpasiyent.getAdres());
    }//GEN-LAST:event_jButtoneditActionPerformed

    private void jButtoncancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtoncancelActionPerformed
        action("Cancel");
    }//GEN-LAST:event_jButtoncancelActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
       if(evt.getClickCount()==2){
           action("Table");
       }
    }//GEN-LAST:event_jTable1MouseClicked

    private void jButtonclearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonclearActionPerformed
        clear();
    }//GEN-LAST:event_jButtonclearActionPerformed

    private void jButtonsaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonsaveActionPerformed

if(!jTextFieldname.getText().equals("")&&!jTextFieldsurname.getText().equals("")&&!jTextFieldpinkod.getText().equals("")&&!jTextFieldphone.getText().equals("")&&!jTextFieldadress.getText().equals("")){


          int id = 0;
if(selectedpasiyent!=null){
        
        id = selectedpasiyent.getIdpasiyent(); } 
        connmysqlxestexana conn = new connmysqlxestexana();
       
       
        
        Pasiyent pas = new Pasiyent(0, jTextFieldname.getText(), jTextFieldsurname.getText(), jTextFieldpinkod.getText(), jTextFieldphone.getText(), jTextFieldadress.getText());
         String index = pas.getPinkod();
        if(jTextFieldpinkod.getText().equals(index)){
        JOptionPane.showMessageDialog(this, "BU PINKOD Tekrarlana bilmez!");}else{
        
        
        pas.setIdpasiyent(id);
        conn.insertupdatepasiyent(pas);
       listofpasiyents = conn.ekranacixarmaemripasiyent("");
       
        fillthetable(listofpasiyents);
        action("can");
        
        selectedpasiyent=null;
        clear();}
        
}else{

JOptionPane.showMessageDialog(null, "Bu xanalar bos qala bilmez!");}      
       
        
        
        
        
    }//GEN-LAST:event_jButtonsaveActionPerformed

    private void jButtondeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtondeleteActionPerformed
     String a = jTable1.getSelectedRow()+"";
    if(a!=null){   
     int index =  jTable1.getSelectedRow();
       
     int id = listofpasiyents.get(index).getIdpasiyent();
         connmysqlxestexana conn = new connmysqlxestexana();
      int n = JOptionPane.showConfirmDialog(this, "Silmeye eminsiz?","Xeberdarliq", JOptionPane.OK_CANCEL_OPTION);
      if(n==0){
       conn.deletepasiyent(id);
      
        listofpasiyents.remove(index);
        fillthetable(listofpasiyents);
      }
        action("a");
         }else{
    
    JOptionPane.showMessageDialog(this, "Secim edin!");
    }
        
     
     
    }//GEN-LAST:event_jButtondeleteActionPerformed

    private void jTextFieldaxtarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldaxtarActionPerformed
       
    }//GEN-LAST:event_jTextFieldaxtarActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
     int index =jComboBox1.getSelectedIndex();
     if(index==0){List<Pasiyent>list = conn.adagoreekranacixarpas(jTextFieldaxtar.getText());
         fillthetable(list);}else{
     if(index==1){List<Pasiyent>list = conn.soyadgoreekranacixpas(jTextFieldaxtar.getText());
         fillthetable(list);
     }else{
     if(index==2){List<Pasiyent>list = conn.pinkodgoreekranacixpas(jTextFieldaxtar.getText());
         fillthetable(list);}else{if(index==3){
             List<Pasiyent>list = conn.telefongoreekranacixpas(jTextFieldaxtar.getText());
             fillthetable(list);
         }}
     }
     }
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jButtaxtarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtaxtarActionPerformed
        if(jTextFieldaxtar.getText().equals("")){
            JOptionPane.showMessageDialog(null, "Zehmet olmasa axtarmaq istediyiniz melumati daxil edin!");
        }
        jComboBox1ActionPerformed(evt);
        
    }//GEN-LAST:event_jButtaxtarActionPerformed

    private void jTable1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_jTable1MouseEntered

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Pasiyentekrani.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Pasiyentekrani.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Pasiyentekrani.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Pasiyentekrani.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Pasiyentekrani dialog = new Pasiyentekrani(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtaxtar;
    private javax.swing.JButton jButtoncancel;
    private javax.swing.JButton jButtonclear;
    private javax.swing.JButton jButtondelete;
    private javax.swing.JButton jButtonedit;
    private javax.swing.JButton jButtonnew;
    private javax.swing.JButton jButtonsave;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextFieldadress;
    private javax.swing.JTextField jTextFieldaxtar;
    private javax.swing.JTextField jTextFieldname;
    private javax.swing.JTextField jTextFieldphone;
    private javax.swing.JTextField jTextFieldpinkod;
    private javax.swing.JTextField jTextFieldsurname;
    // End of variables declaration//GEN-END:variables
}
