/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package jframesehv;



import connmysqlhospital.connmysqlxestexana;
import entityPasiyent.Pasiyent;
import java.util.List;
import javax.swing.JOptionPane;


/**
 *
 * @author Rafael
 */
public class ekran extends javax.swing.JFrame {

    private final List<Pasiyent> listofpasiyent;

    /**
     * Creates new form ekran
     */
    public ekran() {
        initComponents();
        jButtonduzelis.setEnabled(false);
        jButtonsil.setEnabled(false);
        jButtonyaddasaxla.setEnabled(false);
        jButtontemizle.setEnabled(false);
        jTable1.setEnabled(false);
        jTextFieldad.setEnabled(false);
        jTextFieldsoyad.setEnabled(false);
        jTextFieldtelefon.setEnabled(false);
        jTextFieldpinkod.setEnabled(false);
        jTextFieldadress.setEnabled(false);
        connmysqlxestexana conn = new connmysqlxestexana();
        listofpasiyent = conn.ekranacixarmaemripasiyent("");
        fillthetable(listofpasiyent);
        
        
       
   }
public void fillthetable(List<Pasiyent>list){
     int row = 0;
    for (Pasiyent pasiyent : list) {
       jTable1.setValueAt(pasiyent.getAd(), row, 0);
       jTable1.setValueAt(pasiyent.getSoyad(), row, 1);
       jTable1.setValueAt(pasiyent.getPinkod(), row, 2);
       jTable1.setValueAt(pasiyent.getTelefon(), row, 3);
       jTable1.setValueAt(pasiyent.getAdres(), row, 4);
       row++;
    }
}
    
public void clear(){
      jTextFieldad.setText(null);
      jTextFieldsoyad.setText(null);
      jTextFieldtelefon.setText(null);
      jTextFieldadress.setText(null);
      jTextFieldpinkod.setText(null);
      jTextFieldaxtar.setText(null);
     
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelxosgelmisiz = new javax.swing.JLabel();
        jLabelad = new javax.swing.JLabel();
        jLabelsoyad = new javax.swing.JLabel();
        jLabelpinkod = new javax.swing.JLabel();
        jLabeltelefon = new javax.swing.JLabel();
        jLabeladres = new javax.swing.JLabel();
        jTextFieldad = new javax.swing.JTextField();
        jTextFieldsoyad = new javax.swing.JTextField();
        jTextFieldpinkod = new javax.swing.JTextField();
        jTextFieldtelefon = new javax.swing.JTextField();
        jTextFieldadress = new javax.swing.JTextField();
        jButtonpasiyent = new javax.swing.JButton();
        jButtontemizle = new javax.swing.JButton();
        jButtonduzelis = new javax.swing.JButton();
        jButtonaxtar = new javax.swing.JButton();
        jButtonyaddasaxla = new javax.swing.JButton();
        jButtonsil = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabelaxtar = new javax.swing.JLabel();
        jTextFieldaxtar = new javax.swing.JTextField();
        jComboBox1 = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabelxosgelmisiz.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabelxosgelmisiz.setText("Xos gelmisiz!!!");

        jLabelad.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabelad.setText("Ad:");

        jLabelsoyad.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabelsoyad.setText("Soyad:");

        jLabelpinkod.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabelpinkod.setText("Pinkod:");

        jLabeltelefon.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabeltelefon.setText("Telefon:");

        jLabeladres.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabeladres.setText("Adress:");

        jTextFieldsoyad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldsoyadActionPerformed(evt);
            }
        });

        jButtonpasiyent.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jButtonpasiyent.setText("Yeni Pasiyent");
        jButtonpasiyent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonpasiyentActionPerformed(evt);
            }
        });

        jButtontemizle.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jButtontemizle.setText("Temizle");
        jButtontemizle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtontemizleActionPerformed(evt);
            }
        });

        jButtonduzelis.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jButtonduzelis.setText("Duzelis Et");
        jButtonduzelis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonduzelisActionPerformed(evt);
            }
        });

        jButtonaxtar.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jButtonaxtar.setText("Axtar");
        jButtonaxtar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonaxtarActionPerformed(evt);
            }
        });

        jButtonyaddasaxla.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jButtonyaddasaxla.setText("Yadda Saxla");
        jButtonyaddasaxla.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonyaddasaxlaActionPerformed(evt);
            }
        });

        jButtonsil.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jButtonsil.setText("Sil");
        jButtonsil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonsilActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Ad", "Soyad", "PinKod", "Telefon", "Adress"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jLabelaxtar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabelaxtar.setText("Axtar:");

        jTextFieldaxtar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldaxtarActionPerformed(evt);
            }
        });

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Ad", "Soyad", "PinKod", "Telefon" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelpinkod)
                            .addComponent(jLabeltelefon)
                            .addComponent(jLabeladres))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jTextFieldtelefon, javax.swing.GroupLayout.DEFAULT_SIZE, 269, Short.MAX_VALUE)
                            .addComponent(jTextFieldadress))
                        .addGap(23, 23, 23)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButtontemizle, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonpasiyent, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(44, 44, 44)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButtonaxtar, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonduzelis, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(40, 40, 40)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButtonsil, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonyaddasaxla, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(38, 38, 38))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabelxosgelmisiz, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(244, 244, 244))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabelsoyad)
                                    .addComponent(jLabelad))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jTextFieldad, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(10, 10, 10)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jTextFieldsoyad, javax.swing.GroupLayout.DEFAULT_SIZE, 268, Short.MAX_VALUE)
                                            .addComponent(jTextFieldpinkod)))))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabelaxtar, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jTextFieldaxtar, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabelxosgelmisiz, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelad)
                            .addComponent(jTextFieldad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelsoyad)
                            .addComponent(jTextFieldsoyad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelpinkod)
                            .addComponent(jTextFieldpinkod, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabeltelefon, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jTextFieldtelefon, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabeladres)
                            .addComponent(jTextFieldadress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButtonpasiyent, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)
                        .addComponent(jButtontemizle, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButtonduzelis, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)
                        .addComponent(jButtonaxtar, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButtonyaddasaxla, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)
                        .addComponent(jButtonsil, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelaxtar)
                    .addComponent(jTextFieldaxtar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 396, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(22, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldsoyadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldsoyadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldsoyadActionPerformed

    private void jButtonduzelisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonduzelisActionPerformed
        jTable1.getSelectedRow();
    }//GEN-LAST:event_jButtonduzelisActionPerformed

    private void jButtonpasiyentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonpasiyentActionPerformed
     jButtonduzelis.setEnabled(false);
        jButtonsil.setEnabled(false);
        jButtonyaddasaxla.setEnabled(true);
        jButtontemizle.setEnabled(true);
        jButtonpasiyent.setEnabled(false);
       
        jTextFieldad.setEnabled(true);
        jTextFieldsoyad.setEnabled(true);
        jTextFieldtelefon.setEnabled(true);
        jTextFieldpinkod.setEnabled(true);
        jTextFieldadress.setEnabled(true);
        
    }//GEN-LAST:event_jButtonpasiyentActionPerformed

    private void jButtonyaddasaxlaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonyaddasaxlaActionPerformed
       
        if(!jTextFieldad.getText().equals("")&&!jTextFieldsoyad.getText().equals("")&&!jTextFieldpinkod.getText().equals("")&&!jTextFieldtelefon.getText().equals("")&&!jTextFieldadress.getText().equals("")){
        connmysqlxestexana xeste = new connmysqlxestexana();
        Pasiyent pas = new Pasiyent(0, jTextFieldad.getText(), jTextFieldsoyad.getText(), jTextFieldpinkod.getText(), jTextFieldtelefon.getText(), jTextFieldadress.getText());
        xeste.insertupdatepasiyent(pas);
        connmysqlxestexana conn = new connmysqlxestexana();
        List<Pasiyent>list = conn.ekranacixarmaemripasiyent("");
        fillthetable(list);
         clear();}else{
            JOptionPane.showMessageDialog(null, "Bos qala bilmez!!");
        
        }
        jButtonpasiyent.setEnabled(true);
        
    }//GEN-LAST:event_jButtonyaddasaxlaActionPerformed

    private void jButtontemizleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtontemizleActionPerformed
      clear();
    }//GEN-LAST:event_jButtontemizleActionPerformed

    private void jButtonaxtarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonaxtarActionPerformed
      if(jTextFieldaxtar.getText().equals("")){
      JOptionPane.showMessageDialog(null, "Xana bosdur!");
      }else{
      jComboBox1ActionPerformed(evt);
      }
        
       
      
       
    }//GEN-LAST:event_jButtonaxtarActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
      
        jTable1.setEnabled(true);
        
        jTable1.getSelectedRow();
       
    }//GEN-LAST:event_jTable1MouseClicked

    private void jTextFieldaxtarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldaxtarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldaxtarActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
       connmysqlxestexana conn = new connmysqlxestexana();
        int index = jComboBox1.getSelectedIndex();
      
        if(index==0){
        List<Pasiyent>list=conn.adagoreekranacixarpas(jTextFieldaxtar.getText());
              fillthetable(list);}else{
        if(index==1){
        List<Pasiyent>list=conn.soyadgoreekranacixpas(jTextFieldaxtar.getText());
              fillthetable(list);}else{
        if(index==2){
        List<Pasiyent>list = conn.pinkodgoreekranacixpas(jTextFieldaxtar.getText());
              fillthetable(list);}else{
        if(index==3){
        List<Pasiyent>list= conn.telefongoreekranacixpas(jTextFieldaxtar.getText());
              fillthetable(list);   }}}}
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jButtonsilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonsilActionPerformed
       
    }//GEN-LAST:event_jButtonsilActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ekran.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ekran.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ekran.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ekran.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ekran().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonaxtar;
    private javax.swing.JButton jButtonduzelis;
    private javax.swing.JButton jButtonpasiyent;
    private javax.swing.JButton jButtonsil;
    private javax.swing.JButton jButtontemizle;
    private javax.swing.JButton jButtonyaddasaxla;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabelad;
    private javax.swing.JLabel jLabeladres;
    private javax.swing.JLabel jLabelaxtar;
    private javax.swing.JLabel jLabelpinkod;
    private javax.swing.JLabel jLabelsoyad;
    private javax.swing.JLabel jLabeltelefon;
    private javax.swing.JLabel jLabelxosgelmisiz;
    private javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextFieldad;
    private javax.swing.JTextField jTextFieldadress;
    private javax.swing.JTextField jTextFieldaxtar;
    private javax.swing.JTextField jTextFieldpinkod;
    private javax.swing.JTextField jTextFieldsoyad;
    private javax.swing.JTextField jTextFieldtelefon;
    // End of variables declaration//GEN-END:variables
}
